# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false
right_format = "$status$shell$time"

[character] # The name of the module we are configuring is 'character'

[rust]
symbol = '󱘗 '

[haskell]
symbol = '󰲒 '

[shell]
disabled = false

[time]
disabled = false
format = '[at](cyan bold) [$time]($style) '

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[status]
disabled = false
symbol = '󰲼 '
success_symbol = ''
not_executable_symbol = '󱔢 '
not_found_symbol = ' '
sigint_symbol = ' '
signal_symbol = ' '
style = 'bold red'
pipestatus = true
