# the master module name
MODULE:=mux2a2d

# multithreaded simulation model
THREADS:=1

# use this option to specify the top module, remove all other top modules
# should correspond to `MODULE` otherwise this makefile won't work
# left empty to not use
# TOPMODULE=$(MODULE)

# default is `obj_dir`
MDIR:=

# ANYTHING under `INC_D` will be regarded as header files!
# including `.h`, `.hpp` and cxx-styled `algorithm`
INC_D:=include

SIM_FLAGS:=+trace

# after the `RAW_WAVE` file is generated by user's program,
# mv it into `WAVE_D` and rename it corresponding to current modulename
WAVE_D:=wave
RAW_WAVE:=waveform.vcd

# there is a variable named `CXXFLAGS` can be `export` into Vxxx.mk,
# but I prefer a more consistent way to pass it by `--CFLAGS xxx` to verilator
#
# tell `V$(MODULE).mk` to generate debuging information
# VCFLAGS+=-g
VCFLAGS+=-std=gnu++23

# compile all the files in this directory as a single module, recursively searching
MASTER_D:=master

# treat every directory under this directory as a sub module,
# with a modulename the same as its directory name,
# use argument `submodule` to specify which to compile
SUB_D:=sub
