#!/usr/bin/bash

# Increase brightness
inc_backlight() {
	brightnessctl -d amdgpu_bl1 set 10%+
}

# Decrease brightness
dec_backlight() {
	brightnessctl -d amdgpu_bl1 set 10%-
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	brightnessctl -d amdgpu_bl1 g
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	return 1
fi
